### ISSUE TITLE
Backend: add score field to database and edit java class files

### ISSUE THREAD

**Issue by mandev15** [CMU-313/fall22-hw3-g1#3]
- Add score field to database: in workflow configuration and and in event log in each document
- Add score private field to java class files

**Comment by mandev15** [comment]
Time estimate: 4.5 hrs (based on HW2 backend features)
Acceptance criteria: if tests that edit score field (all CRUD operations) are passed

**Comment by shannoding** [comment]
Fixed by #9 and #12
